# Generated by Django 4.2.3 on 2023-07-28 22:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionableChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('color', models.CharField(blank=True, choices=[('blue', 'Blue'), ('green', 'Green'), ('darkgreen', 'Darkgreen'), ('yellow', 'Yellow'), ('red', 'Red'), ('pink', 'Pink'), ('orange', 'Orange'), ('blueviolet', 'Blueviolet'), ('darkmagenta', 'Darkmagenta')], max_length=15)),
                ('archivedStatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sectionedLayer', models.CharField(blank=True, default='2', max_length=10, null=True)),
                ('layer', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('archivedStatus', models.BooleanField(default=False)),
                ('parentSection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TimeTrack2_APP.section')),
            ],
            options={
                'ordering': ['sectionedLayer'],
            },
        ),
        migrations.CreateModel(
            name='SessionTime',
            fields=[
                ('startFrom', models.IntegerField(primary_key=True, serialize=False)),
                ('endTo', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
                ('dateAdded', models.IntegerField()),
                ('dateLastModified', models.IntegerField()),
                ('startFrom', models.IntegerField()),
                ('endTo', models.IntegerField()),
                ('sectionRef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TimeTrack2_APP.section')),
            ],
        ),
        migrations.CreateModel(
            name='Actionable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startFrom', models.IntegerField()),
                ('endTo', models.IntegerField()),
                ('detail', models.CharField(max_length=250, null=True)),
                ('currentSection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='TimeTrack2_APP.section')),
                ('currentSession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='TimeTrack2_APP.sessiontime')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TimeTrack2_APP.actionablechoices')),
            ],
        ),
    ]
