# Generated by Django 4.2.3 on 2023-08-04 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTrack2_APP', '0002_sessiontime_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionable',
            name='currentSession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TimeTrack2_APP.sessiontime'),
        ),
    ]
