# Generated by Django 4.2.3 on 2023-07-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTrack2_APP', '0002_alter_actionable_endto_alter_actionable_startfrom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionable',
            name='epochID',
        ),
        migrations.AlterField(
            model_name='actionable',
            name='endTo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
