# Generated by Django 4.2.3 on 2023-08-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTrack2_APP', '0003_alter_actionable_currentsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionablechoices',
            name='archivedStatus',
        ),
        migrations.AddField(
            model_name='sessiontime',
            name='sessionDetails',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='actionablechoices',
            name='color',
            field=models.CharField(blank=True, choices=[('blue', 'Blue'), ('green', 'Green'), ('darkgreen', 'Darkgreen'), ('yellow', 'Yellow'), ('red', 'Red'), ('pink', 'Pink'), ('orange', 'Orange'), ('blueviolet', 'Blueviolet'), ('darkmagenta', 'Darkmagenta')], max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='actionablechoices',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
