# Generated by Django 4.2.3 on 2023-07-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTrack2_APP', '0003_remove_actionable_epochid_alter_actionable_endto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontime',
            name='endTo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sessiontime',
            name='startFrom',
            field=models.IntegerField(),
        ),
    ]
