# Generated by Django 4.2.7 on 2024-01-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeTrack2_APP', '0004_remove_actionablechoices_archivedstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionablechoices',
            name='color',
            field=models.CharField(blank=True, choices=[('#3498db', 'Blue'), ('#2ecc71', 'Green'), ('#1c7d44', 'Darkgreen'), ('#f1c40f', 'Yellow'), ('#e74c3c', 'Red'), ('#9b59b6', 'Pink'), ('orange', 'Orange'), ('blueviolet', 'Blueviolet'), ('darkmagenta', 'Darkmagenta')], max_length=50, unique=True),
        ),
    ]
